### PR TITLE
Add rapidstring

### PR DESCRIPTION
**Pull request by iamthad**
https://github.com/boyerjohn/rapidstring

### CODE REVIEW

**Comment by TryExceptElse** [comment]
This link appears bad, or the project has been removed.

**Comment by rsachetto** [comment]
I think this is the correct link: https://github.com/mathchq/rapidstring

**Comment by TryExceptElse** [comment]
Do we know if this user has the intention of maintaining the project going forward? I don't see any activity in the last year.

**Comment by rsachetto** [comment]
> Do we know if this user has the intention of maintaining the project going forward? I don't see any activity in the last year.

No, I don't. :)

**Comment by iamthad** [comment]
The library appears to be unmaintained at this point.

**Pull request closed without merging**
