### PR TITLE
Suggesting PR to include libcluon for network and serialization

### PR DESCRIPTION
**Pull request by chrberger**

### CODE REVIEW

**Comment by bullno1** [comment]
It's not single file?

**Comment by Manuzor** [comment]
According to the docs, it is.
> libcluon is distributed as single-file, header-only library - just drop cluon-complete.hpp into your project, #include "cluon-complete.hpp", and compile your project with a modern C++ compiler (C++14 or newer)

They link to `cluon-complete.hpp` with this URL: https://chrberger.github.io/libcluon/headeronly/cluon-complete.hpp

**Comment by bullno1** [comment]
I am confused because of this: https://github.com/chrberger/libcluon/tree/master/libcluon/src

**Comment by Manuzor** [comment]
The catch project is the same. I believe they use multiple files during development and then merge them into a single header for release/distribution.

Single header location: https://github.com/catchorg/Catch2/blob/master/single_include/catch2/catch.hpp
Development headers: https://github.com/catchorg/Catch2/tree/master/include

**Comment by chrberger** [comment]
Hi @bullno1, sorry that I was not clear in my PR about this. As @Manuzor stated correctly, we have separated source and header files for the development.

However, as part of our release process, we package everything (incl. license) into a single-file, header-only library available here: 
https://chrberger.github.io/libcluon/headeronly/cluon-complete.hpp and all previous releases here: https://github.com/chrberger/libcluon/tree/gh-pages/headeronly

I hope that this is clarifying your question?

**Comment by chrberger** [comment]
hi, are there further information necessary where we can help with?

**Comment by nothings** [comment]
No, I just process them in batches and I haven't done a batch in a while.

**Comment by chrberger** [comment]
@nothings great, thanks.

**Comment by chrberger** [comment]
Thank you.

**Pull request merged**
