### PR TITLE
Duplication for catch, adding catch2

### LINKED ISSUE #94: Duplication for catch
Also, catch2 can be added I think

### PR DESCRIPTION
**Pull request by campisano**

### CODE REVIEW

**Comment by nothings** [comment]
A few issues:

1. You have an editor set to delete trailing whitespace or something, which is causing a lot of extra junk in the diffs (look at 'files changed' tab in this thread). Can you submit that as a separate PR with no real changes, just the whitespace? You shouldn't need to change these ones, once I merge that one these should be clearer.

2. What is up with these titles ("Close #93", "Closed #94")?

**Comment by campisano** [comment]
1) sure, I will change that
2) I forgot to define a title, and the pull request automatically get the commit text I think. I will rename them

**Comment by campisano** [comment]
Mmm probably there is no need to close...

**Comment by campisano** [comment]
removed trailing space restored

**Pull request merged**
