### PR TITLE
Added SFML in 2d Graphics

### PR DESCRIPTION
**Pull request by ghost**
link: https://github.com/SFML/SFML

### CODE REVIEW

**Comment by saucecode** [comment]
SFML is not a single file library..?

**Comment by ghost** [comment]
I researched and found out its not? you can research and update if i am wrong. ( if(mistake==true) return Sorry; )

**Comment by saucecode** [comment]
All good. SFML is a great libray in its own right

**Comment by ghost** [comment]
yes!

**Pull request closed without merging**
